# Generated by Django 4.2.5 on 2024-01-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.tarmada.com%2Frestaurants&psig=AOvVaw0BpjGWN3zd6GVtElnDwomd&ust=1704590110232000&source=images&cd=vfe&ved=0CBIQjRxqFwoTCIjbxpPLx4MDFQAAAAAdAAAAABAE",
                max_length=500,
            ),
        ),
    ]
